<a href="https://colab.research.google.com/github/PrikhodkoMA/Math_prac/blob/Hometask_2/Homework_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Задача 1:


Почему-то не работает, если не заводить под нулевую матрицу отдельную переменную

In [ ]:
import numpy as np
a = np.fill_diagonal(np.zeros((5, 5), int)[1 : 5][0 : 4], [1, 2, 3, 4])
print(a)
del a

None


Если разбить на доп перменные, то работает:

In [ ]:
import numpy as np
a = np.zeros((5, 5), int)
np.fill_diagonal(a[1 : 5][0 : 4], [1, 2, 3, 4])
print(a)
del a

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


Задача 2: не получилось без циклов


In [ ]:
import numpy as np
a = np.ones((10, 3))
b = np.zeros(10, int)
for i in range(10):
  for j in range(3):
    if abs(a[i][j] - 0.5) < abs(a[i][b[i]] - 0.5): b[i] = j;
  b[i] = a[i][b[i]]
print(b)
del a, b

[1 1 1 1 1 1 1 1 1 1]


Задача 3:

In [ ]:
import numpy as np
a = np.random.random((6, 6))
np.sum(a, axis = 1) / np.max(a, axis = 0)
del a

Задача 4: не получилось без цикла

In [ ]:
import numpy as np
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
mask = []
for i in range(1, len(x)):
  if x[i - 1] == 0: mask.append(i)
print(np.max(x[mask]))
del x, i, mask

Задача 5: не получилось без цикла

In [ ]:
import numpy as np
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
for j in i:
  x[j] += 1
print(x)
del x, i, j

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


Задача 6:

In [ ]:
import numpy as np
a = np.random.rand(10)
print(a)
a.round()

[0.90980784 0.303138   0.58714846 0.66784536 0.83763891 0.63262326
 0.81446884 0.03996382 0.21239616 0.34749942]


array([1., 0., 1., 1., 1., 1., 1., 0., 0., 0.])

In [ ]:
import numpy as np
a = np.random.rand(10)
print(a)
a = (a + 0.5) // 1
print(a)

[0.98963595 0.77645353 0.82085085 0.62804709 0.10119861 0.67728519
 0.47268672 0.6141237  0.89556905 0.84410846]
[1. 1. 1. 1. 0. 1. 0. 1. 1. 1.]


In [ ]:
import numpy as np
a = np.random.rand(10)
print(a)
for i in range(len(a)):
  if(a[i] % 1 < 0.5): 
    a[i] -= a[i] % 1
  else: a[i] = a[i] - a[i] % 1 + 1
print(a)

[0.00198994 0.61322198 0.53144195 0.48128573 0.98638517 0.15572842
 0.49967614 0.39062921 0.08961324 0.49889184]
[0. 1. 1. 0. 1. 0. 0. 0. 0. 0.]
